// <auto-generated />
using System;
using ConcurReportingDatabaseServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcurReporting.Domain.Migrations
{
    [DbContext(typeof(ConcurContext))]
    [Migration("20260331115151_updatedFieldLengths")]
    partial class updatedFieldLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcurReporting.Domain.Models.QueryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QueryHistoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QueryHistories", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AllocationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("Account1")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("ConcurID")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ConcurID"), 90);

                    b.HasIndex("EntryId");

                    b.HasIndex("ItemizationId");

                    b.HasIndex("CompanyCode", "CostCenterCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("CompanyCode", "CostCenterCode"), 90);

                    b.HasIndex("CompanyCode", "CostCenterCode", "Account");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("CompanyCode", "CostCenterCode", "Account"), 90);

                    b.ToTable("Allocations", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EntryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AllocationType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("BillRuleRegOrRateNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyCardTransactionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContractOrRFPTitleAndIdentifyingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractTitleIdentifyingNumberAndDate")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("EntrySubtractFromGross")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ExpenseID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExpenseTypeCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExpenseTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasAppliedCashAdvance")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAttendees")
                        .HasColumnType("bit");

                    b.Property<bool>("HasComments")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExceptions")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVAT")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImageRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaidByExpensePay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonalCardCharge")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsGiven")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LengthInHours")
                        .HasColumnType("int");

                    b.Property<string>("LocationCountryISO2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationSubdivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatureOfContact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NetTaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NonTaxDeductibleVATAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NonTaxableNonDeductibleAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PersonDesignatedInContractOrRFP")
                        .HasMaxLength(200)
                        .HasColumnType("bit");

                    b.Property<bool?>("PersonalChargeConfirmation")
                        .HasColumnType("bit");

                    b.Property<decimal>("PostedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProposedService")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ReceiptReceived")
                        .HasColumnType("bit");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("SpendCategoryCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpendCategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxDeductibleVATAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxInvoiceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxReceiptType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("TaxReclaimAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TaxReclaimCountryRegion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxableDeductibleAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TransactionCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TripID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VendorDescription")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VendorListItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConcurID")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ConcurID"), 90);

                    b.HasIndex("JourneyId")
                        .IsUnique()
                        .HasFilter("[JourneyId] IS NOT NULL");

                    b.HasIndex("ReportId");

                    b.HasIndex("CompanyCode", "CostCenterCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("CompanyCode", "CostCenterCode"), 90);

                    b.ToTable("Entries", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Itemization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemizationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AllocationType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("BillRuleRegOrRateNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContractOrRFPTitleAndIdentifyingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractTitleIdentifyingNumberAndDate")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EntrySubtractFromGross")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ExpenseTypeCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExpenseTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasComments")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExceptions")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImageRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsGiven")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LengthInHours")
                        .HasColumnType("int");

                    b.Property<string>("LocationCountryISO2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationSubdivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatureOfContact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NetTaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NonTaxDeductibleVATAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NonTaxableNonDeductibleAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("PersonDesignatedInContractOrRFP")
                        .HasMaxLength(200)
                        .HasColumnType("bit");

                    b.Property<bool?>("PersonalChargeConfirmation")
                        .HasColumnType("bit");

                    b.Property<decimal>("PostedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProposedService")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpendCategoryCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpendCategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxDeductibleVATAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxInvoiceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TaxReclaimAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TaxReclaimCountryRegion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxableDeductibleAmount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VATCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConcurID")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ConcurID"), 90);

                    b.HasIndex("EntryId");

                    b.HasIndex("CompanyCode", "CostCenterCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("CompanyCode", "CostCenterCode"), 90);

                    b.ToTable("Itemizations", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JourneyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessDistance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<int?>("OdometerEnd")
                        .HasColumnType("int");

                    b.Property<int?>("OdometerStart")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDistance")
                        .HasColumnType("int");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Journeys", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDueCompanyCard")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AmountDueEmployee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ApprovalStatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApproverLoginID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApproverName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryISO2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountrySubdivision")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeGroup")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EverSentBack")
                        .HasColumnType("bit");

                    b.Property<bool>("HasException")
                        .HasColumnType("bit");

                    b.Property<string>("LastComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LedgerName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerLoginID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatusCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentStatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PersonalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PolicyID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ProcessingPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReceiptsReceived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalApprovedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalClaimedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UserDefinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ApprovalStatusCode"), 90);

                    b.HasIndex("ApproverLoginID");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ApproverLoginID"), 90);

                    b.HasIndex("ConcurID")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("ConcurID"), 90);

                    b.HasIndex("PaymentStatusCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("PaymentStatusCode"), 90);

                    b.HasIndex("CompanyCode", "CostCenterCode");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("CompanyCode", "CostCenterCode"), 90);

                    b.ToTable("Reports", "cnc");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Allocation", b =>
                {
                    b.HasOne("ConcurReportingDatabaseServices.Models.Entry", "Entry")
                        .WithMany("Allocations")
                        .HasForeignKey("EntryId");

                    b.HasOne("ConcurReportingDatabaseServices.Models.Itemization", "Itemization")
                        .WithMany("Allocations")
                        .HasForeignKey("ItemizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Entry");

                    b.Navigation("Itemization");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Entry", b =>
                {
                    b.HasOne("ConcurReportingDatabaseServices.Models.Journey", "Journey")
                        .WithOne("Entry")
                        .HasForeignKey("ConcurReportingDatabaseServices.Models.Entry", "JourneyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConcurReportingDatabaseServices.Models.Report", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Itemization", b =>
                {
                    b.HasOne("ConcurReportingDatabaseServices.Models.Entry", "Entry")
                        .WithMany("Itemizations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Entry", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Itemizations");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Itemization", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Journey", b =>
                {
                    b.Navigation("Entry")
                        .IsRequired();
                });

            modelBuilder.Entity("ConcurReportingDatabaseServices.Models.Report", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
